import BackLink from "../../common/BackLink/BackLink";
import UnderHeader from "../../common/underHeader/UnderHeader"
import styles from "./ControlData.module.css";

const ControlData = () => {
    return(
        <>
            <UnderHeader/>
            <div className={styles.container}>
                <BackLink title='Назад' />
                <p className={styles.text}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem dolorem aliquid, consectetur doloribus reiciendis vitae aliquam doloremque expedita, nulla amet, consequuntur minima. Iure inventore totam hic expedita ducimus fuga repellat eius, natus illum excepturi facilis repellendus obcaecati, architecto dolorum veritatis eos incidunt, impedit aut corrupti deserunt ipsa? Quibusdam accusamus dicta, vel a impedit ex eligendi fuga iste rem deserunt consequuntur iusto sunt illo, reprehenderit dolor ullam placeat obcaecati? Totam qui maxime neque suscipit a, ex labore. Harum, corporis eum neque quisquam ducimus maiores itaque fugit sequi, ipsam, voluptates tempore exercitationem consectetur assumenda. Fugit quis aliquid quisquam odio laborum, eveniet quidem recusandae, voluptates ratione in molestias sequi omnis blanditiis magnam dolore repellendus consequatur maiores qui aut modi soluta atque ea? Non ea voluptas et dolor, sequi velit perspiciatis libero voluptate, vitae ullam eum vero itaque quo. Blanditiis necessitatibus perferendis repudiandae consectetur quisquam repellat ut ex facilis corrupti, aspernatur sunt ipsa iste? Adipisci illum ad cumque eos deserunt quidem voluptatem quaerat in illo neque consequuntur eligendi aut assumenda nemo, possimus perspiciatis autem quasi praesentium inventore sit hic ab optio mollitia culpa? Alias esse eos quos ex cupiditate dolores voluptate quam laborum cumque necessitatibus. Totam provident possimus corrupti dignissimos. Itaque sunt magni temporibus pariatur amet architecto accusamus aliquam, a repellendus sequi! Commodi explicabo asperiores molestiae expedita sint nulla sapiente officiis cupiditate earum. Exercitationem porro fugiat iusto voluptas dolores cumque, harum eligendi iure fugit ratione magnam aperiam perferendis similique, qui facere quis magni quos quia dolorum, corrupti rerum laudantium. Amet dolorum nam ut quia iste neque laboriosam iure eos quidem ea, modi dolore numquam nisi dicta eum id repudiandae! Est repudiandae ex voluptatibus mollitia voluptas numquam omnis commodi maxime voluptatem illo obcaecati et dolorem, culpa vitae voluptates explicabo quibusdam, eum enim tempore? Provident nam at suscipit earum? Qui iure a, error officiis obcaecati animi.
                </p>
                <p className={styles.text}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem dolorem aliquid, consectetur doloribus reiciendis vitae aliquam doloremque expedita, nulla amet, consequuntur minima. Iure inventore totam hic expedita ducimus fuga repellat eius, natus illum excepturi facilis repellendus obcaecati, architecto dolorum veritatis eos incidunt, impedit aut corrupti deserunt ipsa? Quibusdam accusamus dicta, vel a impedit ex eligendi fuga iste rem deserunt consequuntur iusto sunt illo, reprehenderit dolor ullam placeat obcaecati? Totam qui maxime neque suscipit a, ex labore. Harum, corporis eum neque quisquam ducimus maiores itaque fugit sequi, ipsam, voluptates tempore exercitationem consectetur assumenda. Fugit quis aliquid quisquam odio laborum, eveniet quidem recusandae, voluptates ratione in molestias sequi omnis blanditiis magnam dolore repellendus consequatur maiores qui aut modi soluta atque ea? Non ea voluptas et dolor, sequi velit perspiciatis libero voluptate, vitae ullam eum vero itaque quo. Blanditiis necessitatibus perferendis repudiandae consectetur quisquam repellat ut ex facilis corrupti, aspernatur sunt ipsa iste? Adipisci illum ad cumque eos deserunt quidem voluptatem quaerat in illo neque consequuntur eligendi aut assumenda nemo, possimus perspiciatis autem quasi praesentium inventore sit hic ab optio mollitia culpa? Alias esse eos quos ex cupiditate dolores voluptate quam laborum cumque necessitatibus. Totam provident possimus corrupti dignissimos. Itaque sunt magni temporibus pariatur amet architecto accusamus aliquam, a repellendus sequi! Commodi explicabo asperiores molestiae expedita sint nulla sapiente officiis cupiditate earum. Exercitationem porro fugiat iusto voluptas dolores cumque, harum eligendi iure fugit ratione magnam aperiam perferendis similique, qui facere quis magni quos quia dolorum, corrupti rerum laudantium. Amet dolorum nam ut quia iste neque laboriosam iure eos quidem ea, modi dolore numquam nisi dicta eum id repudiandae! Est repudiandae ex voluptatibus mollitia voluptas numquam omnis commodi maxime voluptatem illo obcaecati et dolorem, culpa vitae voluptates explicabo quibusdam, eum enim tempore? Provident nam at suscipit earum? Qui iure a, error officiis obcaecati animi.
                </p>
            </div>
        </>
    )
}

export default ControlData;